name: Building testing, containerization and deployment 

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo 
        uses: actions/checkout@v2
      # this Action should follow steps to set up Python build environment
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v3
        with:
          path: "homeservice-backend/requirements.txt"
          update-pip: "false"
          update-setuptools: "false"
          update-wheel: "false"
