name: Building testing, containerization and deployment 

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo 
        uses: actions/checkout@v2
      - name: install python version 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      # this Action should follow steps to set up Python build environment
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v3
        with:
          path: "homeservice-backend/requirements.txt"
          update-pip: "false"
          update-setuptools: "false"
          update-wheel: "false"

      - name: install node version 16
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: 'npm'
          cache-dependency-path: homeservice-frontend/package-lock.json
      - name: install dependencies
        run: |
         cd homeservice-frontend/  
         npm install

  tests:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Testing Applications
        uses: actions/checkout@v2
      #testing for django application
      - name: Testing Djnago Application
        run: pip install pytest
          pytest
      #testing for vue application
      - name: Testing Vue Application
        run: |
          cd homeservice-frontend/ 
          