name: Building testing, containerization and deployment 

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo 
        uses: actions/checkout@v2
      - name: checkout files  # for backend (django-app)
        uses: Bhacaz/checkout-files@v2